# Generated by Django 3.2.25 on 2024-11-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_alter_customersignup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='address',
            field=models.CharField(blank=True, default='Chicago,USA', max_length=250, null=True),
        ),
    ]
